export const FETCH_EVENTS_INIT = "FETCH_EVENTS_INIT";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED";
export const ADD_EVENT_INIT = "ADD_EVENT_INIT";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILED = "ADD_EVENT_FAILED";
// export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED";